### PR TITLE
PR raised for changes in MA

### PR DESCRIPTION
**Pull request by kunalrjadhav3**
Changes are made in MA

### CODE REVIEW

**Comment by kunalrjadhav3** [comment]
Good job

**Comment by kunalrjadhav3git** [comment]
What is this comment for in MA?

**Review by kunalrjadhav3git — CHANGES_REQUESTED** [review]
Change the comment to Raised PR

**Comment by kunalrjadhav3** [comment]
> Change the comment to Raised PR

Done

**Review by kunalrjadhav3git — DISMISSED** [review]

**Review by kunalrjadhav3git — CHANGES_REQUESTED** [review]
Rename comment to master branch

**Review by kunalrjadhav3git — APPROVED** [review]

**Pull request merged**
